Updated package configuration to pyproject.toml from setup.cfg
nilp0inter/experta pull request #38
Opened 2024-12-25 01:53 UTC by dougransom

pyproject.toml now specifies the packaging, test parameters, and dependencies.

`pip install -e .[dev]` for editable install with development dependancies.
`python -m build` to build the packages.
`pytest` to run the tests.

2024-12-25 02:05 UTC, dougransom commented
i have not tested the travis file update, I don't know how.

2024-12-25 17:57 UTC, dougransom commented
Can you squash-merge after approval please, instead of merging all commits.

2024-12-25 18:57 UTC, dougransom commented
if this is approved, a next step could be to switch to [uv](https://docs.astral.sh/[uv](https://docs.astral.sh/uv/)/) and 

[tox-uv[(https://pypi.org/project/tox-uv/) .

2025-02-08 17:07 UTC, nilp0inter requested changes

2025-02-08 17:07 UTC, nilp0inter commented on pyproject.toml
> +"tox",
Shouldn't this be a dev dependency as well?

2025-02-08 17:07 UTC, nilp0inter commented on pyproject.toml
> +"tox",
ping @dougransom

2025-02-09 14:04 UTC, dougransom commented on pyproject.toml
> +"tox",
@nilp0inter I think the tox dependency should only be in the [dev] list.  I have made that change.

2025-02-09 15:12 UTC, nilp0inter approved these changes

2025-02-09 15:12 UTC, merged